lib/tasks/geo_combine.rake
Ensure the `tmp` directory exists on the file system before cloning
=> Ensure tmp directory exists

geo_combine.gemspec, lib/geo_combine.rb, lib/geo_combine/formats.rb, lib/geo_combine/geoblacklight.rb, lib/geo_combine/subjects.rb, lib/schema/geoblacklight-schema.json, lib/xslt/iso2geoBL.xsl, spec/fixtures/docs/basic_geoblacklight.json, spec/fixtures/docs/full_geoblacklight.json, spec/fixtures/json_docs.rb, spec/fixtures/xml_docs.rb, spec/lib/geo_combine/geoblacklight_spec.rb, spec/lib/geo_combine/iso19139_spec.rb, spec/spec_helper.rb
This pull request significantly improves support for GeoBlacklight-Schema. GeoBlacklight-Schema has moved away from being xml based to JSON based and this pull request modifies GeoCombine with this change in mind by doing the following.
- it creates a way to validate geoblacklight-schema json using the schema validation from https://github.com/geoblacklight/geoblacklight-schema/blob/master/geoblacklight-schema.json
- it modifies `iso2geoBL.xsl` to output json that is almost compliant geoblacklight-schema
- provides a way to create `GeoCombine::Geoblacklight` objects that do the following:
- can be created with a valid JSON string of geoblacklight-schema
- output valid json using `#to_json`
- can take a `fields` argument as a `Hash` that merges with the original metadata
- provides an …
=> adds in basic geoblacklight schema validation and geoblacklight enhancment metadata

geo_combine.gemspec, lib/xslt/iso2html.xsl, spec/features/iso2html_spec.rb, spec/helpers.rb, spec/spec_helper.rb
A big thanks to @kimdurante for the work she did on `iso2html.xsl`. Will need to add enhanced testing with a new static html Capybara driver.
Partially addresses #18
=> Creates semantically valid iso19139 to html

lib/xslt/iso2geoBL.xsl
georss_polygon_s XML field was missed commenting out field names, producing invalide JSON for indexing
fixes #24
=> Remove extraneous XML line

lib/geo_combine/geoblacklight.rb
This PR uses a schema fragment to validate the document, and we don't need to validate the schema itself too.
=> use schema fragment to validate data

lib/geo_combine.rb, lib/geo_combine/exceptions.rb, lib/geo_combine/geoblacklight.rb, spec/lib/geo_combine/geoblacklight_spec.rb
=> validate dct_references as parseable serialized json string

lib/xslt/iso2html.xsl
I couldn't get this file to validate in Oxygen until I moved a </dl> from line 1067 to line 534.  This version now works using XSLT transform in Oxygen.  I haven't tried it within a GeoCombine script.
=> Moved closing dl tag

lib/geo_combine/geoblacklight.rb
=> add arguments to to_json for compatability with Rails

lib/geo_combine/geoblacklight.rb, spec/fixtures/docs/geoblacklight_pre_v1.json, spec/fixtures/json_docs.rb, spec/lib/geo_combine/geoblacklight_spec.rb
@mejackreed This PR will upgrade to a v1 schema if `.enhance_metadata` is called. It also makes some changes for rubocop complaints.
=> add upgrade_to_v1 logic to convert pre_v1 to v1 schema

lib/geo_combine/version.rb
Do https://github.com/OpenGeoMetadata/GeoCombine/pull/87 and other improvements from the last release (https://github.com/OpenGeoMetadata/GeoCombine/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+merged%3A%3E2017-08-01+) include any breaking changes?  From what I could assess they appear to be backwards-compatible.
Resolves #88
=> Updating the version to release 0.4.0

lib/geo_combine/geo_blacklight_harvester.rb, spec/lib/geo_combine/geo_blacklight_harvester_spec.rb
=> Ensure that the format param is always appended to paged catalog urls

lib/geo_combine/geo_blacklight_harvester.rb, spec/lib/geo_combine/geo_blacklight_harvester_spec.rb
Fixes #100
Since GeoBlacklight v2.0.0, and the introduction of our bbox overlap ratio feature, Solr will automatically generate fields and values for these four coordinates:
* solr_bboxtype__minX
* solr_bboxtype__minY
* solr_bboxtype__maxX
* solr_bboxtype__maxY
These fields need to be removed before harvested documents can be sent to Solr for indexing.
=> GBL Harvester: default document_transformer should delete solr_bboxtype fields

Gemfile, geo_combine.gemspec, lib/tasks/geo_combine.rake, spec/lib/geo_combine/geo_blacklight_harvester_spec.rb, spec/lib/tasks/geo_combine_spec.rb
I was having errors when I was trying to use the solr indexing, based on the errors it looks like the gem version lock was no longer working and we have to switch to the new faraday net http persistent, so that's what I tried to do here
=> Fix solr indexing

.github/workflows/ruby.yml
When testing on ruby 3.0, we need to specify the version as a string,
otherwise YAML will interpret 3.0 as the integer 3. This causes the
actual requirement to become ~3, which allows for downloading e.g.
Ruby v3.2 when we wanted v3.0.
See for example:
https://github.com/OpenGeoMetadata/GeoCombine/actions/runs/3897283862/jobs/6654792458#step:3:11
=> Ensure CI is locked to ruby v3.0

lib/geo_combine/indexer.rb, lib/tasks/geo_combine.rake
This fixes an issue where we try to print the active solr URL
when geocombine:index is invoked, but the Indexer doesn't know it,
causing Rake to report that the number of arguments is wrong.
=> Support querying the configured solr url when indexing

lib/geo_combine.rb, lib/geo_combine/migrators/v1_aardvark_migrator.rb, spec/fixtures/docs/full_geoblacklight_aardvark.json, spec/fixtures/json_docs.rb, spec/lib/geo_combine/migrators/v1_aardvark_migrator_spec.rb
- Sketch initial migrator for v1 to aardvark
- Convert all the keys, and the metadata version value
Advances #121, see that issue for remaining work
=> Add initial class for aardvark migration

lib/geo_combine/harvester.rb, lib/tasks/geo_combine.rake, spec/lib/geo_combine/harvester_spec.rb
Providing both `directory` and `path` to Git.clone results in
the repo being cloned into a directory nested inside itself.
We don't need to provide `directory` (using the default of the repo's name is fine), and we actually want `path` to be the OpenGeoMetadata root (default `tmp/opengeometadata`) instead of the repo's name.
This may be a fix for #144.
=> Avoid nesting cloned OGM repos inside themselves

lib/geo_combine/harvester.rb, spec/lib/geo_combine/harvester_spec.rb
- Ensure correct handling of OGM repos with no data
- Improve console output for harvest tasks
output looked a little confusing when harvesting/indexing multiple repos at a time (e.g. you'd see "Cloned 0 repositories" because things were skipped if you already had the repo locally). this cleans up the output and makes sure we handle the empty repositories in the OGM namespace.
=> Harvesting reporting / tests

.github/workflows/ruby.yml, .rubocop.yml
This switches CI to use the automatic `bundle install` and caching
functionality provided by the setup-ruby action:
https://github.com/ruby/setup-ruby#caching-bundle-install-automatically
Also ensures we get latest bundler — not sure why we were installing a particular version in CI.
=> Use the automatic bundling and caching of the setup-ruby action

lib/geo_combine/harvester.rb
We don't want to accidentally harvest testing data from here when invoking clone/pull.
=> Add gbl-1_to_aardvark repo to harvesting denylist

.gitignore, lib/geo_combine/harvester.rb, spec/lib/geo_combine/harvester_spec.rb
HT @karenmajewicz
This PR allows GeoCombine to harvest all repositories by passing a `per_page` param along with the API call.
```
ewlarson@beanburrito .internal_test_app % bundle exec rake geocombine:clone --trace
** Invoke geocombine:clone (first_time)
** Execute geocombine:clone
Cloned https://github.com/OpenGeoMetadata/shared-repository.git
Cloned https://github.com/OpenGeoMetadata/edu.stanford.purl.git
Cloned https://github.com/OpenGeoMetadata/edu.princeton.arks.git
Cloned https://github.com/OpenGeoMetadata/edu.virginia.git
Cloned https://github.com/OpenGeoMetadata/edu.nyu.git
Cloned https://github.com/OpenGeoMetadata/edu.harvard.git
Cloned https://github.com/OpenGeoMetadata/edu.umn.git
Cloned https://github.com/OpenGeoMetadata/edu.tufts.git
Cloned …
```
=> Add: a per_page param to OGM API URI

lib/geo_combine/harvester.rb, spec/lib/geo_combine/harvester_spec.rb
This change was suggested by @hudajkhan to handle cases where the
user specifically requests to clone a repository that might be
archived (or empty).
We still perform the action, but issue a warning.
=> Warn if cloning an empty or archived OGM repo

lib/geo_combine/harvester.rb, lib/geo_combine/ogp.rb
Hi folks! 
We're working on a small CLI gem for our in-house GBL that uses GeoCombine. We hit a small bug with `GeoCombine::Harvester`. calling `.repositories` throws:
```sh 
NameError:
uninitialized constant GeoCombine::Harvester::Net
```
from this line https://github.com/OpenGeoMetadata/GeoCombine/blob/2d59072b8e0221b258f78353f8299a625e8889c5/lib/geo_combine/harvester.rb#L104
Adding an explicit `require 'net/http'` to `harvester.rb` solved it; this PR includes that & a small second commit to make rubocop test pass (edit: looks redundant with #157?)
Spec tests passed locally on ruby-3.2.2.
=> Bug: Explicit require net/http

.gitignore, lib/geo_combine/migrators/v1_aardvark_migrator.rb
`v1_aardvark_migrator` was failing when `RESOURCE_CLASS_MAP[@v1_hash['dc_type_s']` and `RESOURCE_TYPE_MAP[@v1_hash['layer_geom_type_s']` returned `nil` when `gsub` was called (`lib/geo_combine/migrators/v1_aardvark_migrator.rb:54` and `lib/geo_combine/migrators/v1_aardvark_migrator.rb:55`)
- add save-nav method (`&`) to `gsub`
- make guard clause for `is_part_of` explicit (will handle `nil`)
=> GBL --> Aardvark Migrator Refactors

README.md, lib/geo_combine/migrators/v1_aardvark_migrator.rb, spec/fixtures/docs/full_geoblacklight.json, spec/fixtures/docs/full_geoblacklight_aardvark.json, spec/lib/geo_combine/migrators/v1_aardvark_migrator_spec.rb
- Handle elements without crosswalk (via lookup tables)
- Support migrating collections in dct_isPartOf_sm
- Convert single to multivalued fields where appropriate
- Retain custom fields and remove deprecated fields
Closes #121
=> Schema v1 to Aardvark migrator

.github/workflows/ruby.yml, .rubocop.yml, README.md, geo_combine.gemspec, lib/geo_combine/ckan_metadata.rb, lib/geo_combine/geo_blacklight_harvester.rb, lib/geo_combine/geoblacklight.rb, lib/geo_combine/harvester.rb, lib/geo_combine/indexer.rb, lib/geo_combine/logger.rb, lib/tasks/geo_combine.rake, spec/lib/geo_combine/geo_blacklight_harvester_spec.rb, spec/lib/geo_combine/harvester_spec.rb, spec/lib/geo_combine/indexer_spec.rb, spec/lib/geo_combine/migrators/v1_aardvark_migrator_spec.rb, spec/spec_helper.rb
This admittedly large PR happened because I wanted to set up regularly scheduled updates from OpenGeoMetadata for Earthworks via `cron`, and GeoCombine seemed like the best way to do it (https://github.com/sul-dlss/earthworks/issues/639).
It tackles several outstanding issues:
- Removes support for EOL and near-EOL ruby versions 2.7 and 3.0, rubocops things to match 3.1
- Uses a batch indexing strategy for the OGM indexer, which allows for indexing almost all the records in OGM in under 10 minutes (on my laptop, at least)
- Adds logging capabilities to the indexers and harvester (#138)
- Makes indexing report and continue gracefully instead of failing when solr reports that the metadata is bad (#168)
- Makes indexing try again if the connection to solr drops
- If we're indexing and …
=> Make OGM tasks more production-ready

lib/geo_combine/migrators/v1_aardvark_migrator.rb, spec/fixtures/docs/full_geoblacklight_aardvark.json
Previously we were setting dcat_bbox but not locn_geometry based
on the v1 solr_geom. The latter is also crucial, because we can't
do spatial search or render previews without it.
This ensures that we always populate locn_geometry if we had solr_geom,
and then also fill in dcat_bbox if the geometry happens to be in the
ENVELOPE() format.
=> Ensure that locn_geometry is populated when migrating v1 to Aardvark

README.md, lib/geo_combine/harvester.rb, spec/lib/geo_combine/harvester_spec.rb
This changes the indexer so that when you do:
```sh
rake geocombine:index
```
It prefers Aardvark format records by default (instead of 1.0), since that's now the current standard. You can still do:
```sh
SCHEMA_VERSION='1.0' rake geocombine:index
```
To index v1.0 instead.
It also updates the README to add this info (and a little bit of other info).
=> Use Aardvark as the default format for indexing records

lib/geo_combine/indexer.rb, spec/lib/geo_combine/indexer_spec.rb
During indexing, when the number of documents is greater than the batch size, a document is skipped each iteration.
- Add spec that exercises the situation.
- Use `.each_slice` for a cleaner way to slice up document list into batches.
Addresses #172
=> Batch Indexing Fix
