OpenGeoMetadata/GeoCombine

- .coveralls.yml
adds in a coveralls.yml to hopefully fix coveralls reporting
> add coveralls.yml

- lib/tasks/geo_combine.rake
Should close #25 
Update command takes the form of a JSON array
tagging @waynegraham
> update takes the form of a json array

- lib/xslt/fgdc2geoBL.xsl
- lib/xslt/iso2geoBL.xsl
- spec/lib/geo_combine/fgdc_spec.rb
> Modify xslt

- README.md
- bin/geocombine
- geo_combine.gemspec
- lib/geo_combine/cli.rb
- lib/geo_combine/version.rb
I would like to be able to run this as a command line tool outside of any specific application. If I'm alone in this, I'm happy to maintain a fork, but I figured I would see if there was any interest.
> Add command line interface using thor

- README.md
> update readme to provide information about SOLR_URL environment variable

- lib/geo_combine/geoblacklight.rb
- spec/lib/geo_combine/geoblacklight_spec.rb
This PR improves the validation testing.
> do individual field checks for validation

- lib/tasks/geo_combine.rake
> add whitelist support for geocombine:clone

- geo_combine.gemspec
> relax deps on bundler and rake

- README.md
- lib/tasks/geo_combine.rake
And cleans up the README a bit
>  add SOLR_COMMIT_WITHIN option for geocombine:index

- README.md
> update README for clarity

- Gemfile
- lib/geo_combine/formatting.rb
- lib/geo_combine/ogp.rb
- spec/lib/geo_combine/formatting_spec.rb
- spec/lib/geo_combine/ogp_spec.rb
- spec/spec_helper.rb
@mejackreed This PR introduces some cleanup heuristics that were used 3 yrs ago to generate slugs for the OGP metadata.
> improve slugification logic

- geo_combine.gemspec
- lib/geo_combine/ogp.rb
> add activesupport for present?

- lib/geo_combine.rb
- lib/geo_combine/railtie.rb
This PR fixes #64 
@mejackreed
> add Rails tie for rake task loading

- geo_combine.gemspec
- lib/tasks/geo_combine.rake
> use net-http-persistent for geocombine:index task

- lib/xslt/iso2html.xsl
- spec/features/iso2html_spec.rb
Fixes https://github.com/sul-dlss/earthworks/issues/635
Checkout https://github.com/OpenGeoMetadata/GeoCombine/pull/93/commits/5a6cf0ab2237d9b58d20e3bf0d13fac7564bff79 for the readable diff
> Use valid HTML DL for iso2html xsl

- README.md
- lib/tasks/geo_combine.rake
> Fix harvester index task and README

- README.md
Just something useful for all the Mac folks to know! Also seeing if I can make prs
> Add zsh tip to readme

- lib/geo_combine/ogp.rb
> Rename list of values to strip

- lib/geo_combine/harvester.rb
- spec/lib/geo_combine/harvester_spec.rb
> Skip harvesting of repositories that have been archived

- lib/geo_combine/ogp.rb
> Use .compact instead of filtering out nil

- spec/lib/geo_combine/harvester_spec.rb
> Combine rspec stubs with receive_messages
